In [8]:
import pandas as pd
df=pd.read_csv('customer_data.csv')

In [9]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount,Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,18.0,Male,Hoodie,Outerwear,21,New Hampshire,L,Pink,Fall,4.1,Yes,Express,Yes,No,46,UPI,Quarterly
1,2,43.0,Female,Sandals,Footwear,64,Idaho,M,Maroon,Winter,4.4,Yes,Express,No,No,2,Cash,Monthly
2,3,25.0,Female,Pants,Clothing,47,Mississippi,M,Gray,Winter,4.5,Yes,Next Day,Yes,No,17,PayPal,Monthly
3,4,59.0,Female,Coat,Outerwear,39,Arizona,XL,Green,Summer,2.9,Yes,Next Day,Yes,Yes,34,Debit Card,Fortnightly
4,5,NaN,Female,Coat,Outerwear,91,Pennsylvania,M,Green,Spring,3.4,Yes,Standard,Yes,Yes,16,PayPal,Bi-Weekly

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             100 non-null    int64
 1   Age                     92 non-null     float64
 2   Gender                  92 non-null     object
 3   Item Purchased          100 non-null    object
 4   Category                100 non-null    object
 5   Purchase Amount         100 non-null    int64
 6   Location                100 non-null    object
 7   Size                    100 non-null    object
 8   Color                   92 non-null     object
 9   Season                  100 non-null    object
 10  Review Rating           92 non-null     float64
 11  Subscription Status     100 non-null    object
 12  Shipping Type           100 non-null    object
 13  Discount Applied        100 non-null    object
 14  Promo Code Used         100 non-null    object
 15  Previous Purchases      100 non-null    int64
 16  Payment Method          92 non-null     object
 17  Frequency of Purchases  100 non-null    object
dtypes: float64(2), int64(3), object(13)
memory usage: 9.1+ KB

In [5]:
df.describe()

,Customer ID,Age,Purchase Amount,Review Rating,Previous Purchases
count,100.000000,100.00000,100.000000,100.000000,100.000000
mean,50.500000,42.77000,52.750000,3.563000,23.140000
std,29.011492,14.25798,26.958769,0.893371,13.368152
min,1.000000,18.00000,10.000000,2.000000,3.000000
25%,25.750000,31.00000,28.750000,2.700000,11.750000
50%,50.500000,43.00000,53.000000,3.650000,22.000000
75%,75.250000,57.00000,78.250000,4.325000,34.000000
max,100.000000,65.00000,100.000000,5.000000,50.000000

In [11]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount,Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,100.000000,92.000000,92,100,100,100.000000,100,100,92,100,92.000000,100,100,100,100,100.000000,92,100
unique,NaN,NaN,2,15,4,NaN,44,4,7,4,NaN,2,5,2,2,NaN,5,5
top,NaN,NaN,Female,Blazer,Footwear,NaN,Wisconsin,M,Black,Winter,NaN,Yes,Free Shipping,No,Yes,NaN,Debit Card,Bi-Weekly
freq,NaN,NaN,57,11,31,NaN,6,26,20,27,NaN,53,23,55,56,NaN,22,32
mean,50.500000,40.673913,NaN,NaN,NaN,56.270000,NaN,NaN,NaN,NaN,3.495652,NaN,NaN,NaN,NaN,26.570000,NaN,NaN
std,29.011492,15.279886,NaN,NaN,NaN,26.827867,NaN,NaN,NaN,NaN,0.923433,NaN,NaN,NaN,NaN,15.001855,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,25.750000,26.750000,NaN,NaN,NaN,34.750000,NaN,NaN,NaN,NaN,2.800000,NaN,NaN,NaN,NaN,12.000000,NaN,NaN
50%,50.500000,39.000000,NaN,NaN,NaN,56.000000,NaN,NaN,NaN,NaN,3.550000,NaN,NaN,NaN,NaN,29.000000,NaN,NaN
75%,75.250000,55.000000,NaN,NaN,NaN,79.250000,NaN,NaN,NaN,NaN,4.325000,NaN,NaN,NaN,NaN,40.000000,NaN,NaN
max,100.000000,65.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [12]:
df.isnull().sum()

Customer ID               0
Age                       8
Gender                    8
Item Purchased            0
Category                  0
Purchase Amount           0
Location                  0
Size                      0
Color                     8
Season                    0
Review Rating             8
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            8
Frequency of Purchases    0
dtype: int64

In [22]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [23]:
df.isnull().sum()

Customer ID               0
Age                       8
Gender                    8
Item Purchased            0
Category                  0
Purchase Amount           0
Location                  0
Size                      0
Color                     8
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            8
Frequency of Purchases    0
Review rating             0
dtype: int64

In [24]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [25]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [26]:
df['Color'] = df['Color'].fillna(df['Color'].mode()[0])

In [27]:
df['Payment Method'] = df['Payment Method'].fillna(df['Payment Method'].mode()[0])

In [28]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount           0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
Review rating             0
dtype: int64

In [29]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

In [30]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'review_rating'],
      dtype='object')

In [31]:
#create a column age_group
labels = ['Young Adult','Adult','Middle aged','Senior']
df['age_group'] =pd.qcut(df['age'], q=4, labels = labels)

In [35]:
df[['age','age_group']].head(15)

    age    age_group
0    18  Young Adult
1    43  Middle aged
2    25  Young Adult
3    59       Senior
4    39        Adult
5    35        Adult
6    59       Senior
7    28  Young Adult
8    39        Adult
9    27  Young Adult
10   34        Adult
11   39        Adult
12   62       Senior
13   21  Young Adult
14   44  Middle aged

In [34]:
df['age'] = df['age'].astype(int)

In [40]:
#create purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly':7,
    'Monthly':30,
    'Quaterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months:':90
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [50]:
df[['purchase_frequency_days','frequency_of_purchases']].head(15)

    purchase_frequency_days frequency_of_purchases
0                        14              Quarterly
1                        30                Monthly
2                        30                Monthly
3                        14            Fortnightly
4                        14              Bi-Weekly
5                        14              Bi-Weekly
6                        14              Bi-Weekly
7                        14              Quarterly
8                        14              Bi-Weekly
9                         7                 Weekly
10                       14              Bi-Weekly
11                        7                 Weekly
12                       14            Fortnightly
13                        7                 Weekly
14                       30                Monthly

In [47]:
df['purchase_frequency_days']=df.groupby('category')['purchase_frequency_days'].transform(lambda x: x.fillna(x.median()))

In [49]:
df['purchase_frequency_days'] = df['purchase_frequency_days'].astype(int)

In [51]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes              No
1               No              No
2              Yes              No
3              Yes             Yes
4              Yes             Yes
5              Yes              No
6               No              No
7              Yes              No
8              Yes              No
9               No              No